export default {
  products: [
    {
      _id: '1',
      name: 'Bata Shoes',
      category: 'Shoes',
      image: '/ShoeImages/Bata1.jpg',
      price: 60,
      brand: 'Bata',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Bata Shoes',
      category: 'Shoes',
      image: '/ShoeImages/Bata2.jpg',
      price: 50,
      brand: ' Bata',
      rating: 4.2,
      numReviews: 5
    },
    {
      _id: '3',
      name: 'Bata Shoes',
      category: 'Shoes',
      image: '/ShoeImages/Bata3.jpg',
      price: 70,
      brand: ' Bata',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'Bata Shoes',
      category: 'Shoes',
      image: '/ShoeImages/Bata4.jpg',
      price: 55,
      brand: ' Bata',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Mocassion',
      category: 'Mens',
      image: '/ShoeImages/Micassino1.jpg',
      price: 45,
      brand: ' Mocassion',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: '6',
      name: 'North Start',
      category: 'Mens',
      image: '/ShoeImages/North-Start1.jpg',
      price: 60,
      brand: ' North Star',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
    },
    {
      _id: '7',
      name: 'Power Shoes',
      category: 'Mens',
      image: '/ShoeImages/p1.jpg',
      price: 70,
      brand: 'Power',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: '8',
      name: 'Power Shoes',
      category: 'Shoes',
      image: '/ShoeImages/power1.jpg',
      price: 40,
      brand: 'Power',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
        {
      _id: '9',
      name: 'Weinbenner',
      category: 'men',
      image: '/ShoeImages/WeinBrenner1.jpg',
      price: 50,
      brand: 'WeinBrenner',
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: '10',
      name: 'Bata-Women',
      category: 'women',
      image: '/ShoeImages/Bata-Women.jpg',
      price: 30,
      brand: 'bata',
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: '11',
      name: 'Bata Shoes',
      category: 'Shoes',
      image: '/ShoeImages/Bata1.jpg',
      price: 20,
      brand: 'Bata',
      rating: 4.5,
      numReviews: 9,
      countInStock: 6,
    },
  ]
}