export default {
  products: [
    {
      _id: '1',
      name: 'Spark-Men',
      category: 'men',
      image: '/ShoeImages/Spark-Men.jpg',
      price: 60,
      brand: 'Spark',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Tommy Takkies-Men',
      category: 'men',
      image: '/ShoeImages/TommyTakkies-Men.jpg',
      price: 50,
      brand: ' Bata',
      rating: 4.2,
      numReviews: 5
    },
    {
      _id: '3',
      name: 'Power-Women',
      category: 'women',
      image: '/ShoeImages/Power-Women.jpg',
      price: 70,
      brand: ' Power',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'Bata Shoes',
      category: 'men',
      image: '/ShoeImages/Bata4.jpg',
      price: 70,
      brand: ' Bata',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Mocassion',
      category: 'men',
      image: '/ShoeImages/Micassino1.jpg',
      price: 80,
      brand: ' Mocassino',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: '6',
      name: 'North Start',
      category: 'men',
      image: '/ShoeImages/North-Start1.jpg',
      price: 90,
      brand: ' North Start',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
    },
    {
      _id: '7',
      name: 'Power Shoes',
      category: 'men',
      image: '/ShoeImages/p1.jpg',
      price: 110,
      brand: 'Power',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: '8',
      name: 'Power Shoes',
      category: 'men',
      image: '/ShoeImages/power1.jpg',
      price: 80,
      brand: 'Power',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '9',
      name: 'Weinbenner',
      category: 'Mens',
      image: '/ShoeImages/WeinBrenner1.jpg',
      price: 60,
      brand: 'Mens',
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
  ]
}