// eslint-disable-next-line
export default {
  products: [
    {
      _id: "1",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Shoes",
      image: "/images/item-1.jpg",
      price: 60,
      brand: "Bata",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "WOMENS MINAM MEAGHAN",
      category: "Shoes",
      image: "/images/item-2.jpg",
      price: 50,
      brand: " Bata",
      rating: 4.2,
      numReviews: 5,
    },
    {
      _id: "3",
      name: "MENS TAJA COMMISSIONER",
      category: "Shoes",
      image: "/images/item-3.jpg",
      price: 70,
      brand: " Bata",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "RUSS MENS SNEAKERS",
      category: "Shoes",
      image: "/images/item-4.jpg",
      price: 70,
      brand: " Bata",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-5.jpg",
      price: 80,
      brand: " Mocassion",
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: "6",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-6.jpg",
      price: 90,
      brand: " North Star",
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
    },
    {
      _id: "7",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-7.jpg",
      price: 110,
      brand: "Power",
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: "8",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Shoes",
      image: "/images/item-8.jpg",
      price: 80,
      brand: "Power",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "9",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-9.jpg",
      price: 45,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "10",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-10.jpg",
      price: 40,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "11",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-11.jpg",
      price: 50,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "12",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-12.jpg",
      price: 55,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "13",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-13.jpg",
      price: 85,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "14",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-14.jpg",
      price: 80,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "15",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-15.jpg",
      price: 65,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "16",
      name: "WOMENS BOOTS SHOES MACA",
      category: "Mens",
      image: "/images/item-16.jpg",
      price: 70,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
    {
      _id: "17",
      name: "MENS SHOES ",
      category: "Mens",
      image: "/ShoeImages/Bata1.jpg",
      price: 70,
      brand: "Mens",
      rating: 4.5,
      numReviews: 8,
      countInStock: 7,
    },
  ],
};
