// eslint-disable-next-line
export default {
    products: [
      {
        _id: '1',
        name: 'WOMENS BOOTS SHOES MACA',
        category: 'Shoes',
        image: '/images/item-1.jpg',
        price: 2999,
        brand: 'Bata',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'WOMENS MINAM MEAGHAN',
        category: 'Shoes',
        image: '/images/item-2.jpg',
        price: 1999,
        brand: ' Bata',
        rating: 4.2,
        numReviews: 5
      },
      {
        _id: '3',
        name: 'MENS TAJA COMMISSIONER',
        category: 'Shoes',
        image: '/images/item-3.jpg',
        price: 2000,
        brand: ' Bata',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      }, {
        _id: '4',
        name: 'RUSS MENS SNEAKERS',
        category: 'Shoes',
        image: '/images/item-4.jpg',
        price: 2200,
        brand: ' Bata',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'WOMENS BOOTS SHOES MACA',
        category: 'Mens',
        image: '/images/item-5.jpg',
        price: 1800,
        brand: ' Mocassion',
        rating: 4.5,
        numReviews: 8,
        countInStock: 4,
      },
      {
        _id: '6',
        name: 'MEMS SNEAKERS',
        category: 'Mens',
        image: '/images/item-6.jpg',
        price: 1900,
        brand: ' North Star',
        rating: 4.5,
        numReviews: 8,
        countInStock: 5,
      },
      {
        _id: '7',
        name: 'MENS BOOTS SHOES',
        category: 'Mens',
        image: '/images/item-7.jpg',
        price: 1100,
        brand: 'Power',
        rating: 4.5,
        numReviews: 8,
        countInStock: 4,
      },
      {
        _id: '8',
        name: 'MENS BOOTS',
        category: 'Shoes',
        image: '/images/item-8.jpg',
        price: 1600,
        brand: 'Power',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '9',
        name: 'MENS Racing Kit Shoes',
        category: 'Mens',
        image: '/images/item-9.jpg',
        price: 2500,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '10',
        name: 'WOMENS Sandal',
        category: 'Mens',
        image: '/images/item-10.jpg',
        price: 1400,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '11',
        name: 'MENS Running Shoes',
        category: 'Mens',
        image: '/images/item-11.jpg',
        price: 1900,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '12',
        name: 'MENS BOOTS',
        category: 'Mens',
        image: '/images/item-12.jpg',
        price: 1550,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '13',
        name: 'Kids BOOTS SHOES',
        category: 'Mens',
        image: '/images/item-13.jpg',
        price: 1850,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '14',
        name: 'WOMENS BOOTS SHOES',
        category: 'Mens',
        image: '/images/item-14.jpg',
        price: 1799,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '15',
        name: 'MENS SHOES',
        category: 'Mens',
        image: '/images/item-15.jpg',
        price: 1499,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      {
        _id: '16',
        name: 'WOMENS SHOES',
        category: 'Mens',
        image: '/images/item-16.jpg',
        price: 1500,
        brand: 'Mens',
        rating: 4.5,
        numReviews: 8,
        countInStock: 7,
      },
      
    ]
  }